import { StyleSheet,  } from 'react-native'

export const webStyles = StyleSheet.create({
  safeContainer: {
    backgroundColor: '#FFF1D5',
    width: '100%',
    height: '100%',
    paddingVertical: 20,
  },
  container: {
    position: 'relative',
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 0,
    left: 20,
    backgroundColor: '#9EC6F3',
    borderRadius: 8,
    paddingHorizontal: 20,
  },
  backButtonText: {
    color: 'white',
  },
  header: {
    backgroundColor: 'white',
    width: '80%',
    height: '20%',
    justifyContent: 'center',
    borderRadius: 8,
    marginTop: 50,
    marginBottom: 10,
  },
  headerText: {
    textAlign: 'center',
    color: '#3C2F60',
    fontWeight: 'bold',
    fontSize: 24,
  },
  titleContainer: {
    backgroundColor: 'white',
    width: '80%',
    borderRadius: 8,
    flexDirection: 'row',
    marginVertical: 10,
  },
  textPrimary: {
    color: '#3C2F60',
    fontWeight: 'bold',
    fontSize: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  textSecondary: {
    color: '#3C2F60',
    fontWeight: 500,
    fontSize: 16,
  },
  textField: {
    paddingHorizontal: 10,
    width: '100%',
  },
  correctAnswerField: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    borderRadius: 8,
  },
  questionContainer: {
    position: 'relative',
    backgroundColor: 'white',
    width: '80%',
    height: '60%',
    borderRadius: 8,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  numOfCard: {
    alignSelf: 'flex-start',
    marginLeft: 15,
    backgroundColor: 'white',
    borderRadius: 8,
  },
  questionCardHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rightSideHeader: {
    width: '20%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginRight: 15,
  },
  editButton: {
    backgroundColor: "#9EC6F3",
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  deleteButton: {
    backgroundColor: "#9EC6F3",
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  quizTokenContainer: {
    width: '100%',
    height: '20%',
    backgroundColor: 'black',
  },
  questionCard: {
    backgroundColor: '#BDDDE4',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    width: '95%',
    height: '100%',
    alignItems: 'center',
  },
  question: {
    backgroundColor: 'white',
    width: '95%',
    borderRadius: 8,
    marginTop: 10,
    marginBottom: 20,
  },
  questionInputText: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginVertical: 10,
    marginHorizontal: 10,
    width: '97%',
  },
  questionChoices: {
    width: '95%',
  },
  choiceLetter: {
    backgroundColor: 'white',
    width: '100%',
    borderRadius: 8,
    flexDirection: 'row',
    marginVertical: 10,
  },
  choiceInputField: {
    paddingHorizontal: 10,
    width: '100%',
  },
  buttonArea: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  addNewButton: {
    backgroundColor: '#9EC6F3',
    borderRadius: 8,
    width: '30%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButton: {
    backgroundColor: '#9EC6F3',
    borderRadius: 8,
    width: '30%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    color:  'white',
  },
  editMode: {
    backgroundColor: '#9EC6F3',
  },
  editModeButton: {
    backgroundColor: 'white'
  },
  correctAnswerToggle: {
    justifyContent: 'center',
    alignItems: 'center',
  }
})

export const mobileStyles = StyleSheet.create({
  safeContainer: {
    backgroundColor: '#FFF1D5',
    width: '100%',
    height: '100%',
    paddingVertical: 20,
  },
  container: {
    position: 'relative',
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 0,
    left: 20,
    backgroundColor: '#9EC6F3',
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  backButtonText: {
    color: 'white',
  },
  header: {
    backgroundColor: 'white',
    width: '80%',
    height: '20%',
    justifyContent: 'center',
    borderRadius: 8,
    marginTop: 50,
    marginBottom: 10,
  },
  headerText: {
    textAlign: 'center',
    color: '#3C2F60',
    fontWeight: 'bold',
    fontSize: 24,
  },
  titleContainer: {
    backgroundColor: 'white',
    width: '80%',
    flexDirection: 'row',
    marginVertical: 10,
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  textPrimary: {
    color: '#3C2F60',
    fontWeight: 'bold',
    fontSize: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  textSecondary: {
    color: '#3C2F60',
    fontWeight: 500,
    fontSize: 16,
  },
  textField: {
    paddingHorizontal: 10,
    width: '100%',
  },
  correctAnswerField: {
    backgroundColor: 'white',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 70,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  questionContainer: {
    position: 'relative',
    backgroundColor: 'white',
    width: '95%',
    height: '70%',
    borderRadius: 8,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  numOfCard: {
    alignSelf: 'flex-start',
    marginLeft: 15,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  questionCardHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rightSideHeader: {
    width: '45%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: 15,
  },
  editButton: {
    backgroundColor: "#9EC6F3",
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  deleteButton: {
    backgroundColor: "#9EC6F3",
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  quizTokenContainer: {
    width: '100%',
  },
  questionCard: {
    backgroundColor: '#BDDDE4',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    flexGrow: 1,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  question: {
    backgroundColor: 'white',
    width: '95%',
    marginTop: 10,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  questionInputText: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginVertical: 10,
    marginHorizontal: 10,
    width: '97%',
  },
  questionChoices: {
    width: '95%',
  },
  choiceLetter: {
    position: 'relative',
    height: 100,
    backgroundColor: 'white',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginVertical: 10,
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  choiceInputField: {
    position: 'absolute',
    bottom: 0,
    paddingHorizontal: 10,
    width: '100%',
  },
  buttonArea: {
    position: 'absolute',
    bottom: -20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  addNewButton: {
    backgroundColor: '#9EC6F3',
    width: '30%',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  saveButton: {
    backgroundColor: '#9EC6F3',
    width: '30%',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  saveButtonText: {
    color:  'white',
  },
  editMode: {
    backgroundColor: '#9EC6F3',
  },
  editModeButton: {
    backgroundColor: 'white'
  },
  correctAnswerToggle: {
    justifyContent: 'center',
    alignItems: 'center',
  }
})