import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeContainer: {
    position: 'relative',
    width: '100%',
    height: '100%',
    backgroundColor: '#FFF1D5',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 40,
  },
  backButton: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#9EC6F3',
    width: '25%',
    height: 50,
    marginTop: '5%',
    marginLeft: '5%',
    justifyContent: 'center',
    alignItems: 'center', 
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  resultCard: {
    backgroundColor: '#BDDDE4',
    width: '80%',
    height: '60%',
    gap: 20,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  resultCardMainBody: {
    position: 'relative',
    backgroundColor: 'white',
    width: '90%',
    height: 250,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  resultTextTitle: {
    position: 'absolute',
    left: 20,
    top: 20,
    width: '100%',
    textAlign: 'left',
    fontWeight: 'bold',
    fontSize: 24,
    color: '#3C2F60',
  },
  resultText: {
    width: '100%',
    textAlign: 'center',
    color: '#3C2F60',
    fontWeight: 'bold',
    fontSize: 24,
  },
  buttonReviewAnswers: {
    backgroundColor: '#9EC6F3',
    width: '90%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  },
  okButton: {
    backgroundColor: '#9EC6F3',
    width: '50%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgb(42, 15, 63)',
    borderRadius: 10,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    elevation: 0,
  }
})